std = "lua51"
max_line_length = false
exclude_files = {
	".luacheckrc"
}
ignore = {
	"212/self", -- Unused argument
	"212/event", -- Unused argument
}
globals = {
	-- Variables
	"BINDING_HEADER_TARGETING",
	"CUSTOM_CLASS_COLORS",
	"DEAD",
	"FACTION_ALLIANCE",
	"FACTION_HORDE",
	"ITEM_QUALITY_COLORS",
	"LEVEL",
	"PVP_ENABLED",
	"RAID_CLASS_COLORS",
	"TOOLTIP_DEFAULT_BACKGROUND_COLOR",
	"UIDROPDOWNMENU_MAXLEVELS",
	"UNKNOWNOBJECT",
	"WOW_PROJECT_BURNING_CRUSADE_CLASSIC",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",

	-- Globals
	"AtlasLootTooltip",
	"AutoCompleteBox",
	"BackdropTemplateMixin",
	"BattlePetTooltip",
	"CalendarContextMenu",
	"CharCustomizeNoHeaderTooltip",
	"CharCustomizeTooltip",
	"ChatMenu",
	"CommunitiesFrame",
	"EmbeddedItemTooltip",
	"EmoteMenu",
	"EventTraceTooltip",
	"FloatingBattlePetTooltip",
	"FrameStackTooltip",
	"FriendsTooltip",
	"GameNoHeaderTooltip",
	"GameSmallHeaderTooltip",
	"GameTooltip",
	"GameTooltipDataMixin",
	"GameTooltipStatusBar",
	"GameTooltipTextLeft1",
	"GameTooltipTextLeft2",
	"GarrisonMissionMechanicFollowerCounterTooltip",
	"GarrisonMissionMechanicTooltip",
	"ItemRefShoppingTooltip1",
	"ItemRefShoppingTooltip2",
	"ItemRefTooltip",
	"ItemSocketingDescription",
	"LanguageMenu",
	"LibDBIconTooltip",
	"LibStub",
	"ManiaTipDB",
	"NamePlateTooltip",
	"PetBattlePrimaryAbilityTooltip",
	"PetBattlePrimaryUnitTooltip",
	"QuestScrollFrame",
	"QueueStatusFrame",
	"QuickKeybindTooltip",
	"RuneforgeFrameResultTooltip",
	"ShoppingTooltip1",
	"ShoppingTooltip2",
	"VoiceMacroMenu",
	
	-- Functions
	"CreateColor",
	"CreateFrame",
	"floor",
	"format",
	"GetFactionInfoByID",
	"GetGuildInfo",
	"GetItemQualityColor",
	"GetLFGDungeonRewardLink",
	"GetLFGDungeonShortageRewardLink",
	"GetMouseFocus",
	"GetQuestGreenRange",
	"GetRealmName",
	"gsub",
	"hooksecurefunc",
	"Mixin",
	"strfind",
	"strmatch",
	"UnitAura",
	"UnitBattlePetLevel",
	"UnitBattlePetType",
	"UnitCanAttack",
	"UnitClass",
	"UnitClassification",
	"UnitCreatureFamily",
	"UnitCreatureType",
	"UnitExists",
	"UnitHealth",
	"UnitHealthMax",
	"UnitIsAFK",
	"UnitIsBattlePetCompanion",
	"UnitIsConnected",
	"UnitIsDead",
	"UnitIsDND",
	"UnitIsPlayer",
	"UnitIsPVP",
	"UnitIsPVPSanctuary",
	"UnitIsTapDenied",
	"UnitIsUnit",
	"UnitIsWildBattlePet",
	"UnitLevel",
	"UnitName",
	"UnitPlayerControlled",
	"UnitQuestTrivialLevelRange",
	"UnitRace",
	"UnitReaction",
	"WrapTextInColorCode",

	-- Namespace
	"C_CreatureInfo",
	"C_PetBattles",
	"C_TradeSkillUI",
	"Enum",
	"Item",
	"ScrollUtil",
	"TooltipDataProcessor",
}